### ISSUE TITLE
add example to add image using customTitle

### ISSUE THREAD

**Issue by chirag04** [Kureev/react-native-navbar#12]
Do you mind adding an example to add image using customTitle?

**Comment by Kureev** [comment]
Honestly, I haven't planned this, because I think that [example with custom elements](https://github.com/Kureev/react-native-navbar/tree/master/examples/customElements) is enough to understand the idea. `customTitle` works totally the same as `customPrev` or `customNext`. All custom elements has a priority against usual ones. Simply put, if you specify `title` prop and `customTitle` prop, then `title` will be ignored.

**Comment by chirag04** [comment]
Sure no problem. I almost got it working and its amazing. Thanks for this component.

The only problem i have though now is how to handle passProps. 

In the component i handle event like this:
```
this.props.navigator.push({
      component: Details,
      passProps: {details: details},
});
```

Can you suggest ideas on how to handle this?

**Comment by chirag04** [comment]
Ok nivermind. I figured how react-native is having it in its source code. 

In the renderScene i need you use ```{...route.passProps}```

Eg:
```
return (
      <View style={styles.navigator}>
        {navBar}
        <Component {...route.passProps} navigator={navigator} route={route} />
      </View>
```

**Comment by iostalk** [comment]
What's the meaning of ...route

**Comment by chirag04** [comment]
https://facebook.github.io/react/docs/jsx-spread.html

``...`` is the spread operator
